dist: bionic
language: java
jdk:
  - openjdk11
services:
  - postgresql
addons:
  postgresql: "10"
before_script:
  - psql -c "ALTER ROLE postgres PASSWORD 'foo'" -U postgres
install:
  # driver
  - if [ "$TRAVIS_BRANCH" != "stable" ]; then git clone --depth 1 --branch dev https://github.com/ldbc/ldbc_snb_driver && cd ldbc_snb_driver && mvn install -DskipTests && cd ..; fi
  # Cypher
  - cd cypher
  - ./get-neo4j.sh
  - . environment-variables-neo4j.sh
  - ./configure-neo4j.sh
  - cd ..
script:
  # Postgres
  - chmod 755 ~
  - cd postgres/load-scripts
  - export PG_CSV_DIR=$(pwd)/../test-data
  - ./load.sh
  - cd ../..
  # Cypher
  - cd cypher
  - export NEO4J_CSV_POSTFIX=_0_0.csv
  - export NEO4J_CSV_DIR=`pwd`/test-data
  - cd scripts
  - ./convert-csvs.sh
  - ./import-to-neo4j.sh
  - ./restart-neo4j.sh
  - cd ../..
  # tests
  - mvn test -B
notifications:
  slack: ldbcouncil:JRXP43nDV4KRgtclmoNZJpyq
  email: false
  on_success: change
  on_failure: always
