version: 2.1
orbs:
  slack: circleci/slack@3.4.2
workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - stable

jobs:
  test:
    resource_class: large
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt update
            # install dependencies
            sudo apt install -y curl git wget unzip maven netcat
            # driver
            git clone --depth 1 --branch dev https://github.com/ldbc/ldbc_snb_driver && cd ldbc_snb_driver && mvn install -DskipTests && cd ..
            # PostgreSQL
            sudo apt install -y postgresql
            # hack: overwrite existing pg_hba.conf file
            sudo bash -c 'echo > /etc/postgresql/12/main/pg_hba.conf'
            sudo bash -c 'echo "local all postgres trust" >> /etc/postgresql/12/main/pg_hba.conf'
            sudo bash -c 'echo "host all all 127.0.0.1/32 trust" >> /etc/postgresql/12/main/pg_hba.conf'
            sudo /etc/init.d/postgresql start
      - run:
          name: Download data
          command: |
            git clone --branch gh-pages --depth 1 https://github.com/ldbc/ldbc_snb_datagen
      - run:
          name: Load
          command: |
            # PostgreSQL
            cd postgres
            export PG_USER=postgres
            export PG_CSV_DIR=`pwd`/../ldbc_snb_datagen/social_network-csv-merge-foreign
            scripts/load.sh
            cd ..
            # Cypher
            cd cypher
            . scripts/environment-variables-default.sh
            scripts/load-in-one-step.sh
            cd ..
      - run:
          name: Test
          command: mvn test -B
      - slack/status
