version: 2.1
orbs:
  slack: circleci/slack@3.4.2
workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - stable

jobs:
  test:
    resource_class: large
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt update
            # install dependencies
            sudo apt install -y wget unzip
            cypher/scripts/install-dependencies.sh
      - run:
          name: Download data
          command: |
            mkdir test-data/
            cd test-data
            wget -q https://ldbc.github.io/ldbc_snb_datagen_spark/social-network-sf0.003-bi-composite-projected-fk-no-header.zip
            unzip -q social-network-sf0.003-bi-composite-projected-fk-no-header.zip
            cd ..
      - run:
          name: Test Cypher toolchain
          command: |
            # Cypher
            export NEO4J_CSV_DIR=`pwd`/test-data/social-network-sf0.003-bi-composite-projected-fk-no-header/csv/bi/composite-projected-fk/
            cd cypher
            . scripts/environment-variables-default.sh
            scripts/load-in-one-step.sh
            python3 batches-cypher.py ${NEO4J_CSV_DIR}
            cd ..
      #     python3 bi.py
      - slack/status
