version: 2.1
orbs:
  slack: circleci/slack@3.4.2
workflows:
  version: 2
  build:
    jobs:
      - test


jobs:
  test:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt update
            # install dependencies
            sudo apt install -y wget unzip
            scripts/install-dependencies.sh
      - run:
          name: Download data sets
          command: |
            ## test data
            mkdir test-data/
            cd test-data
            # Neo4j
            wget -q https://ldbcouncil.org/ldbc_snb_datagen_spark/social-network-sf0.003-bi-composite-projected-fk-neo4j.zip
            unzip -q social-network-sf0.003-bi-composite-projected-fk-neo4j.zip
            wget -q https://ldbcouncil.org/ldbc_snb_datagen_spark/social-network-sf0.003-bi-composite-projected-fk-neo4j-compressed.zip
            unzip -q social-network-sf0.003-bi-composite-projected-fk-neo4j-compressed.zip
            # Umbra
            wget -q https://ldbcouncil.org/ldbc_snb_datagen_spark/social-network-sf0.003-bi-composite-merged-fk.zip
            unzip -q social-network-sf0.003-bi-composite-merged-fk.zip
            cd ..
      - run:
          name: Download factors
          command: |
            wget -q https://ldbcouncil.org/ldbc_snb_datagen_spark/social-network-sf0.003-bi-factors.zip
            unzip social-network-sf0.003-bi-factors.zip -d .
            mv social-network-sf0.003-bi-factors/factors/csv/raw/composite-merged-fk/* paramgen/factors/
      - run:
          name: Generate parameters
          command: |
            paramgen/scripts/paramgen.sh
      - run:
          name: Test Cypher toolchain with uncompressed CSVs
          command: |
            export NEO4J_CSV_DIR=`pwd`/test-data/social-network-sf0.003-bi-composite-projected-fk-neo4j/graphs/csv/bi/composite-projected-fk/
            cypher/scripts/load-in-one-step.sh
            cypher/scripts/batches.sh
            cd ..
      - run:
          name: Test Cypher toolchain with compressed CSVs
          command: |
            export NEO4J_CSV_DIR=`pwd`/test-data/social-network-sf0.003-bi-composite-projected-fk-neo4j-compressed/graphs/csv/bi/composite-projected-fk/
            export NEO4J_CSV_FLAGS="--compressed"
            cypher/scripts/load-in-one-step.sh
            cypher/scripts/backup-database.sh
            cypher/scripts/batches.sh
            cd ..
      - run:
          name: Test Cypher BI script
          command: |
            export NEO4J_CSV_DIR=`pwd`/test-data/social-network-sf0.003-bi-composite-projected-fk-neo4j/graphs/csv/bi/composite-projected-fk/
            cypher/scripts/restore-database.sh
            cypher/scripts/queries.sh --test
      - slack/status
