version: 2.1
orbs:
  slack: circleci/slack@3.4.2
workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - stable

jobs:
  test:
    resource_class: large
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt update
            # install dependencies
            sudo apt install -y curl git wget unzip maven netcat
            # driver
            git clone --depth 1 --branch dev https://github.com/ldbc/ldbc_snb_driver && cd ldbc_snb_driver && mvn install -DskipTests && cd ..
            # Cypher
            cd cypher
            scripts/install-dependencies.sh
            cd ..
            # PostgreSQL
            # TODO
      - run:
          name: Download data
          command: |
            mkdir test-data/
            cd test-data
            wget -q https://ldbc.github.io/ldbc_snb_data_converter/csv-composite-projected-fk.zip
            unzip csv-composite-projected-fk.zip
            cd ..
      - run:
          name: Load
          command: |
            # PostgreSQL
            # TODO
            # Cypher
            cd cypher
            . scripts/environment-variables-default.sh
            export NEO4J_CSV_DIR=`pwd`/../test-data/csv-composite-projected-fk
            export NEO4J_CSV_POSTFIX=.csv
            scripts/load-in-one-step.sh
            cd ..
      - run:
          name: Run Cypher Python script
          command: |
            cd cypher
            python3 bi.py
      - slack/status
