version: 2.1
orbs:
  slack: circleci/slack@3.4.2
workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - stable

jobs:
  test:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt update
            # install dependencies
            sudo apt install -y wget unzip
            cypher/scripts/install-dependencies.sh
            postgres/scripts/install-dependencies.sh
      - run:
          name: Download data
          command: |
            mkdir test-data/
            cd test-data
            # Neo4j
            wget -q https://ldbc.github.io/ldbc_snb_datagen_spark/social-network-sf0.003-bi-composite-projected-fk-neo4j.zip
            unzip -q social-network-sf0.003-bi-composite-projected-fk-neo4j.zip
            # Postgres
            wget -q https://ldbc.github.io/ldbc_snb_datagen_spark/social-network-sf0.003-bi-composite-merged-fk.zip
            unzip -q social-network-sf0.003-bi-composite-merged-fk.zip
            cd ..
      - run:
          name: Test Cypher toolchain
          command: |
            export NEO4J_CSV_DIR=`pwd`/test-data/social-network-sf0.003-bi-composite-projected-fk-neo4j/graphs/csv/bi/composite-projected-fk/
            cd cypher
            . scripts/environment-variables-default.sh
            scripts/load-in-one-step.sh
            python3 batches.py ${NEO4J_CSV_DIR}
            python3 bi.py
            cd ..
      - run:
          name: Test Postgres toolchain
          command: |
            export POSTGRES_CSV_DIR=`pwd`/test-data/social-network-sf0.003-bi-composite-merged-fk/graphs/csv/bi/composite-merged-fk/
            cd postgres
            scripts/start.sh
            scripts/create-db.sh
            python3 load.py ${POSTGRES_CSV_DIR}
            python3 batches.py ${POSTGRES_CSV_DIR}
            python3 bi.py
            cd ..
      - slack/status
